### PR TITLE
Add `bottom_param` option

### LINKED ISSUE #16: Summed term
Hello!

I was [reading about the Hill equation](https://link.springer.com/content/pdf/10.1007/s00407-012-0098-5.pdf), and I observed that the reported expression of the Hill equation
Proper Hill-equation

lacks a summed term of `bottom` to the right-hand side that is included in the HillFit expression. Where is the HillFit expression of the Hill equation reported in literature, or are the terms mathematically equivalent?

### PR DESCRIPTION
**Pull request by freiburgermsu**
Hello @himoto !

Here is my idea for the bottom_param option. It is a simple boolean argument, where `False` provides zero for the bottom parameter, as you described.

A raise catch is also included, which clarifies a potential error that the user might experience (I experienced it) depending upon the applied dataset.

### CODE REVIEW

**Review by himoto — CHANGES_REQUESTED** [review]
Hi @freiburgermsu, thank you for the amazing updates!
I have a question regarding the condition to raise a ValueError.
Currently, ValueError (line 19-22 in fitting.py) is raised when

```python
if self.x_data[0] <= self.x_data[-1]:
    raise ValueError(...)
```
I think for me, `self.x_data[0] <= self.x_data[-1]` is reasonable and an error should be raised when `self.x_data[0] > self.x_data[-1]`. Am I correct?

**Comment by freiburgermsu** [comment]
Hello @himoto !

Yes, your edit is correct. Thank you for reviewing it :)

Andrew

**Comment by himoto** [comment]
@freiburgermsu, I have fixed the code above but we still need to resolve an IndexError

> FAILED test/test_fitting.py::test_fitting - IndexError: tuple index out of range

**Comment by freiburgermsu** [comment]
Hello @himoto! 

I resolved the bug in my latest push. The `curve_fit` function was essentially interpreting the `bottom_param` argument as being one of the parameters that must be calibrated. The location of redefining the bottom parameter was relocated downstream of this process to not interfere with it.

Thank you :)
    Andrew

**Comment by himoto** [comment]
Hi @freiburgermsu, thanks for resolving the issue.
If I understand your code correctly, what you are trying to do is to assign 0 to `bottom` parameter after parameter fitting.
```python
# here
if not bottom_param:
    popt[1] = 0
```
This does not look nice to me because there might be more appropriate parameter values for `top`, `nH`, or `ec50` when `bottom` is fixed to 0.

In my opinion, the `bottom` parameter must be fixed to 0 during regression when `bottom_param=True`.
Below is my idea. Currently, param[1] is assigned to `bottom` even when `bottom_param=True`.
```python
def _equation(self, x: np.ndarray, *params) -> np.ndarray:
    self.top = params[0]
    self.bottom = params[1]
    self.ec50 = params[2]
    self.nH = params[3]
    
    return self.bottom + (self.top - self.bottom) * x ** self.nH / (
        self.ec50 ** self.nH + x ** self.nH
    )
```

I think this should be the following:

```python
def _equation(self, x: np.ndarray, bottom_param: bool, *params) -> np.ndarray:
    self.top = params[0]
    self.bottom = params[1] if bottom_param else 0
    self.ec50 = params[2]
    self.nH = params[3]
    
    return self.bottom + (self.top - self.bottom) * x ** self.nH / (
        self.ec50 ** self.nH + x ** self.nH
    )
```

Then, the estimated parameter values are based on the assumption that `bottom`=0.
I would be happy if you could give me comments on this plan.

Many thanks,
Hiroaki

**Comment by freiburgermsu** [comment]
@himoto This may cause the same IndexError as before, since the error was originally caused by similar logic 
```python
self.bottom = 0
if bottom_param:
   self.bottom = params[1]
```
to what you propose. Essentially, the additional `bottom_param` argument in the `_equation()` function is incorrectly interpreted by Python to be the first entry of the `params` arguments, and thus an IndexError is launched at `self.nH = params[3]`, since `len(params)=3` at this point instead of `4`.

The solution may be to simply define a second `_equation_bottom()` function for where the user desires the bottom parameter, and then remove the bottom parameter from the `_equation()` function where the user does not want the bottom parameter. The `bottom_param` argument would be passed through the `_get_params()` function, and then the proper equation function would be executed to acquire the proper set of parameters.

**Comment by himoto** [comment]
@freiburgermsu, thanks for the detailed explanation, now I understand the exact cause.
The arguments of `_equation(...)` must be `(self, x: np.ndarray, *params)` and we must not add `bottom_param` here.

> The solution may be to simply define a second _equation_bottom() function for where the user desires the bottom parameter, and then remove the bottom parameter from the _equation() function where the user does not want the bottom parameter. 

Yes, this can resolve the issue, but what about moving `bottom_param` argument to `__init__()` (and setting default to True)?

```python
def __init__(
        self,
        x_data: Union[List[float], np.ndarray],
        y_data: Union[List[float], np.ndarray],
        *,
        bottom_param: bool = True,
) -> None:
        self.x_data = np.array(x_data)
        self.y_data = np.array(y_data)
        self.bottom_param = bottom_param
```

Then, we can call `bottom_param` via `self` and do not need to create another equation function:

```python
def _equation(self, x: np.ndarray, *params) -> np.ndarray:
    self.top = params[0]
    self.bottom = params[1] if self.bottom_param else 0
    self.ec50 = params[2]
    self.nH = params[3]
    
    return self.bottom + (self.top - self.bottom) * x ** self.nH / (
        self.ec50 ** self.nH + x ** self.nH
    )
```

**Comment by freiburgermsu** [comment]
@himoto Yes! This is a brilliant work-around.

**Review by himoto — APPROVED** [review]

**Comment by himoto** [comment]
@freiburgermsu thank you for your comments and updates!

**Pull request merged**
