### PR TITLE
Duplicate equation TXT files

### PR DESCRIPTION
**Pull request by freiburgermsu**
Hello @himoto !

I pulled the latest upstream from the `Himoto/hillfit` repository, and I noticed many duplicate files. This PR deletes them, and adds a line in the README and `fitting.py` that have been forgotten.

Andrew

### CODE REVIEW

**Comment by himoto** [comment]
Hi @freiburgermsu, thanks for the updates!

One question. In the `regression()` function in fitting.py, it seems the `sigfigs` argument is not used in the function. Do we need this?

**Comment by freiburgermsu** [comment]
Hello!

The sigfigs argument was used in printing the `r_sqr` on the figure 
```
# r_sqr = "R\N{superscript two}: " + f"{round(self.r_2, sigfigs)}"
```
which has since been commented. 

Perhaps we can offer this ability to print `r_sqr` per an argument -- e.g. `print_r_sqr: bool` -- of the `fitting()` and `regression()` functions, which allows the user to specify whether they want the `r_sqr` printed? 
```python
# regression()
if print_r_sqr:
    r_sqr = "R\N{superscript two}: " + f"{round(self.r_2, sigfigs)}"
    y_coordinate = 0.7 * y_fit[-1]
    if y_coordinate < y_fit[0]:
        y_coordinate = 1 * y_fit[0]
    x_coordinate = 0.8 * x_fit[-1]
    if x_coordinate < x_fit[0]:
        x_coordinate = 2 * x_fit[0]
   ax.text(x_coordinate, y_coordinate, r_sqr)
```
This would offer the option for those who want it, without forcing it upon others who do not want it. We only need the `sigfigs` argument if we offer this ability to print the `r_sqr`.

**Comment by himoto** [comment]
Hi @freiburgermsu, thank you for your detailed explanation!
I agree with your idea offering `print_r_sqr: bool` argument. I think it would be OK to set `True` as a default value of this argument.
Can you please implement this as you showed in your example code above?

**Comment by freiburgermsu** [comment]
Hello @himoto,

The recent commits embody the conditional ability to print R^2 on a plot, with a default of `True`.

I suspect that many of the duplicate files were generated from errors during conflict resolution in kdiff3. Which software do you use for resolving merge conflicts?

**Comment by himoto** [comment]
Hi @freiburgermsu, thank you for the great work!

I do not use any specific tools to resolve merge conflicts.
I always do followings:
1. Do not work in master branch and make origin/master always up to date with upstream/master.
2. Create a new branch and work in it. When master branch is updated, incorporate changes via
    ```
    git fetch
    git merge origin/master
    ```
3. When a pull request is successfully merged, delete the branch and update origin/master.

I hope this note will be helpful.

Thank you!

**Comment by freiburgermsu** [comment]
The note is helpful! I will explore your approach. 

Thank you :)
    Andrew

**Pull request merged**
