### PR TITLE
Add `curve_fit_kws` to fitting function

### PR DESCRIPTION
**Pull request by himoto**

### CODE REVIEW

**Review by freiburgermsu — APPROVED** [review]
Addition looks great! Thank you :)

Andrew

**Comment by himoto** [comment]
Hi @freiburgermsu, thanks for the review! Regarding [your update](https://github.com/himoto/hillfit/pull/23/commits/f5661f3ba42a907803db1e84d5ce433b8b86f3a2), it's not a good idea to have a mutable default argument, in this case a dictionary ([see here for explanation](https://docs.python-guide.org/writing/gotchas/)). Therefore I made it back to the original one.

**Comment by freiburgermsu** [comment]
Hello @himoto !

Thank you for clarifying mutable default arguments. LGTM seems like a great tool to catch semantic changes.

Thank you,
   Andrew

**Comment by himoto** [comment]
@freiburgermsu No problem. And I released version 0.1.6 which include this update.

**Pull request merged**
